language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "chrisgix-github"
    token:
      secure: "693542063522c25a6e363f8467897b366372fb33"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'